Add documentations for PeriodicSyncEvent.
GoogleChromeLabs/puppy-content pull request #14
Opened 2020-08-03 19:14 UTC by mugdhalakhani

PTAL.

2020-08-03 22:00 UTC, jpmedley requested changes

2020-08-03 22:00 UTC, jpmedley commented on content/en-US/api/PeriodicSyncEvent/PeriodicSyncEvent.md
> +periodic background sync request is registered.
```suggestion
run tasks in the service worker with network connectivity. An instance of this event is passed to the `ServiceWorkerGlobalScope.onperiodicsync` handler on the schedule set when calling `PeriodicSyncManager.register()`.
```

2020-08-04 10:47 UTC, mugdhalakhani commented on content/en-US/api/PeriodicSyncEvent/PeriodicSyncEvent.md
> +periodic background sync request is registered.
Thanks for the suggestion! The schedule set in PeriodicSyncManager.register() doesnt translate to the actual schedule. I have modified the wording a bit to clarify that and kept the rest of your suggestion. PTAL.

2020-08-04 15:33 UTC, jpmedley approved these changes

2020-08-04 15:35 UTC, merged