Add documentation for Web NFC API interfaces
GoogleChromeLabs/puppy-content pull request #21
Opened 2021-01-29 22:03 UTC by reillyeon

2021-02-02 19:16 UTC, jpmedley requested changes
I've been supper happy with the stuff you've been submitting. For perspective, no writer gets through a submission without a few requested changes.

2021-02-02 19:16 UTC, jpmedley commented on content/en-US/api/NDEFReader.md
> +ask the user to touch a tag, and if no tag is found within a certain amount of
```suggestion
It can sometimes be useful to set a time limit on a write operation. For example, you
ask the user to touch a tag, and if no tag is found within a certain amount of
```

2021-02-02 19:16 UTC, jpmedley commented on content/en-US/api/NDEFReader.md
> +  await write("Hello World", { timeout: 5_000 });
```suggestion
  await write("Hello World", { timeout: 5000 });
```

2021-02-02 19:16 UTC, jpmedley commented on content/en-US/api/NDEFReader.md
> +This example shows what happens when scan promise rejects and `readingerror` is
```suggestion
This example shows what happens when a scan promise rejects and `readingerror` is
```

2021-02-02 19:16 UTC, jpmedley commented on content/en-US/api/NDEFReadingEvent.md
> +unneeded work.
Dude! Saving battery life. This is the best example yet of the value of involving engineers in writing this stuff. Thank you. Thank you. Thank you. Thank you.

2021-02-02 19:16 UTC, jpmedley commented on content/en-US/api/NDEFRecord.md
> +External type records can be used to create application defined records. These
```suggestion
Use external type records to create application defined records. These
```

2021-02-02 19:16 UTC, jpmedley commented on content/en-US/api/NDEFRecord.md
> +External type records can be used to create application defined records. These
This change is from passive to active voice, which is considered better writing. 

You're doing such a good job of creating these things, I thought I'd go out on a limb and ask you to up your game.

2021-02-02 19:16 UTC, jpmedley commented on content/en-US/api/NDEFRecord.md
> +type "act" (action), with definition borrowed from smart poster, but used in
```suggestion
type "act" (action), with a definition borrowed from smart poster, but used in
```

2021-02-02 19:16 UTC, jpmedley commented on content/en-US/api/NDEFRecord.md
> +type "act" (action), with definition borrowed from smart poster, but used in
What's "smart poster"?

2021-02-02 23:25 UTC, reillyeon commented on content/en-US/api/NDEFReader.md
> +  await write("Hello World", { timeout: 5_000 });
Why? Place separators improve readability.

2021-02-02 23:25 UTC, reillyeon commented on content/en-US/api/NDEFReadingEvent.md
> +unneeded work.
I can't take credit for this. Most of the examples came right out of the specification text.

2021-02-02 23:25 UTC, reillyeon commented on content/en-US/api/NDEFRecord.md
> +type "act" (action), with definition borrowed from smart poster, but used in
It's a term out of the NDEF specification referring to a type of record which contains structured subfields. It comes from the idea that an NFC tag is embedded in a physical poster or billboard and so makes it "smart" by attaching digital information.

2021-02-03 16:52 UTC, jpmedley approved these changes

2021-02-03 16:52 UTC, merged